export const SRI_LANKA_DISTRICTS = [
  "Ampara",
  "Anuradhapura",
  "Badulla",
  "Batticaloa",
  "Colombo",
  "Galle",
  "Gampaha",
  "Hambantota",
  "Jaffna",
  "Kalutara",
  "Kandy",
  "Kegalle",
  "Kilinochchi",
  "Kurunegala",
  "Mannar",
  "Matale",
  "Matara",
  "Monaragala",
  "Mullaitivu",
  "Nuwara Eliya",
  "Polonnaruwa",
  "Puttalam",
  "Ratnapura",
  "Trincomalee",
  "Vavuniya",
];

export const LOCATION_AUTOCOMPLETE_POLICY = Object.freeze({
  maxQueryLength: 80,
  maxResults: 10,
  cacheTtlMs: 5 * 60 * 1000,
  cacheMaxEntries: 500,
  requestsPerWindow: 30,
  windowMs: 60 * 1000,
});
